# Generated by Django 6.0.4 on 2026-06-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0005_issuereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='category',
            field=models.CharField(choices=[('login_account', 'Login or Account'), ('shipment_submission', 'Shipment Submission'), ('document_upload', 'Document Upload'), ('ocr_extraction', 'OCR / Extraction'), ('duty_computation', 'Duty Computation'), ('wmcda_advisory', 'MCDA Advisory'), ('notifications_email', 'Notifications or Email'), ('dashboard_analytics', 'Dashboard / Analytics'), ('page_display_ui', 'Page Display / UI'), ('other', 'Other')], max_length=40),
        ),
    ]
