# Generated by Django 6.0.4 on 2026-07-15 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0017_shipment_job_order_reference'),
        ('supervisor', '0006_alter_issuereport_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('shipment_submit', 'Shipment Submitted'), ('document_upload', 'Document Uploaded'), ('ocr_run', 'OCR Run'), ('hs_code_update', 'HS Code Updated'), ('computation_save', 'Computation Saved'), ('advisory_generate', 'Shipping Type Advisory Generated'), ('advisory_update', 'Declarant Advisory Updated'), ('status_update', 'Shipment Status Updated'), ('config_update', 'System Configuration Updated'), ('exchange_rate_update', 'Exchange Rate Updated'), ('wmcda_update', 'WMCDA Weights Updated'), ('tariff_update', 'Tariff Schedule Updated'), ('report_download', 'Report Downloaded'), ('shipment_delete', 'Shipment Deleted'), ('issue_update', 'Issue Report Updated')], max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('summary', models.CharField(max_length=240)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='shipments.shipment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='supervisor__created_4eb8e9_idx'), models.Index(fields=['action', '-created_at'], name='supervisor__action_a7e3f5_idx'), models.Index(fields=['user', '-created_at'], name='supervisor__user_id_ec7379_idx'), models.Index(fields=['shipment', '-created_at'], name='supervisor__shipmen_8e0a47_idx')],
            },
        ),
    ]
