# Generated by Django 6.0.4 on 2026-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0007_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('shipment_submit', 'Shipment Submitted'), ('document_upload', 'Document Uploaded'), ('ocr_run', 'OCR Run'), ('hs_code_update', 'HS Code Updated'), ('computation_save', 'Computation Saved'), ('advisory_generate', 'Shipping Type Advisory Generated'), ('advisory_update', 'Declarant Advisory Updated'), ('status_update', 'Shipment Status Updated'), ('config_update', 'System Configuration Updated'), ('exchange_rate_update', 'Exchange Rate Updated'), ('wmcda_update', 'MCDA Weights Updated'), ('tariff_update', 'Tariff Schedule Updated'), ('report_download', 'Report Downloaded'), ('shipment_delete', 'Shipment Deleted'), ('issue_update', 'Issue Report Updated')], max_length=40),
        ),
    ]
