# Generated by Django 6.0.4 on 2026-04-25 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('duty_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('chapter', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hawb_number', models.CharField(max_length=100, unique=True)),
                ('import_type', models.CharField(choices=[('permanent', 'Permanent'), ('repair', 'For Repair'), ('sample', 'Sample')], default='permanent', max_length=20)),
                ('shipment_type', models.CharField(blank=True, choices=[('lcl', 'LCL - Less Container Load'), ('fcl', 'FCL - Full Container Load'), ('air', 'Air Freight')], max_length=10, null=True)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('in_review', 'In Review'), ('for_payment', 'For Payment'), ('submitted', 'Submitted to BOC'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revised', 'For Revision')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('freight_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('insurance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('boc_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('boc_status', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
                ('declarant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Commercial Invoice'), ('packing_list', 'Packing List'), ('airway_bill', 'Airway Bill / Bill of Lading'), ('other', 'Other Supporting Document')], max_length=20)),
                ('file', models.FileField(upload_to='shipment_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipments.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentHSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_suggested', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('hs_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.hscode')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_codes', to='shipments.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='shipments.shipment')),
            ],
        ),
    ]
