# Generated by Django 6.0.4 on 2026-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='Payment receipt uploaded by consignee', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
