# Generated by Django 6.0.4 on 2026-05-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_payment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='import_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('personal', 'Personal Effects'), ('balik_bayan', 'Balik Bayan'), ('courier', 'Courier'), ('sample', 'Sample / Free of Charge'), ('diplomatic', 'Diplomatic')], default='commercial', max_length=20),
        ),
    ]
