# Generated by Django 6.0.4 on 2026-05-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_shipment_import_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('lcl', 'LCL - Less Container Load'), ('fcl', 'FCL - Full Container Load'), ('air', 'Air Freight'), ('land', 'Land Freight')], max_length=10, null=True),
        ),
    ]
