# Generated by Django 6.0.4 on 2026-05-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_alter_shipment_shipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('air', 'Air Freight'), ('sea', 'Sea Freight'), ('lcl', 'LCL - Less Container Load'), ('fcl', 'FCL - Full Container Load'), ('land', 'Land Freight')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='urgency',
            field=models.CharField(choices=[('standard', 'Standard'), ('priority', 'Priority'), ('urgent', 'Urgent'), ('rush', 'Rush / Time-Critical'), ('normal', 'Standard')], default='normal', max_length=10),
        ),
    ]
