# Generated by Django 6.0.4 on 2026-05-23 09:23

from django.db import migrations, models


LEGACY_STATUS_MAP = {
    'draft': 'incoming',
    'pending': 'incoming',
    'in_review': 'arrived',
    'for_payment': 'computed',
    'submitted': 'lodgement',
    'revised': 'for_revision',
}


def forwards_statuses(apps, schema_editor):
    Shipment = apps.get_model('shipments', 'Shipment')
    StatusLog = apps.get_model('shipments', 'StatusLog')
    for old_status, new_status in LEGACY_STATUS_MAP.items():
        Shipment.objects.filter(status=old_status).update(status=new_status)
        StatusLog.objects.filter(old_status=old_status).update(old_status=new_status)
        StatusLog.objects.filter(new_status=old_status).update(new_status=new_status)


def backwards_statuses(apps, schema_editor):
    reverse_map = {
        'incoming': 'pending',
        'arrived': 'in_review',
        'computed': 'for_payment',
        'lodgement': 'submitted',
        'for_revision': 'revised',
    }
    Shipment = apps.get_model('shipments', 'Shipment')
    StatusLog = apps.get_model('shipments', 'StatusLog')
    for old_status, new_status in reverse_map.items():
        Shipment.objects.filter(status=old_status).update(status=new_status)
        StatusLog.objects.filter(old_status=old_status).update(old_status=new_status)
        StatusLog.objects.filter(new_status=old_status).update(new_status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_shipment_shipment_type_alter_shipment_urgency'),
    ]

    operations = [
        migrations.RunPython(forwards_statuses, backwards_statuses),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('arrived', 'Arrived'), ('computed', 'Computed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('for_revision', 'For Revision'), ('lodgement', 'Lodgement'), ('ongoing', 'Ongoing'), ('assessed', 'Assessed'), ('paid', 'Paid'), ('released', 'Released'), ('billed', 'Billed')], default='incoming', max_length=20),
        ),
    ]
