# Generated by Django 6.0.4 on 2026-05-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_alter_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdocument',
            name='ocr_fields_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='ocr_quality',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='ocr_ran_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
