# Generated by Django 6.0.4 on 2026-05-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_shipmentdocument_ocr_fields_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='deficiency_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='deficiency_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='deficiency_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='has_deficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='import_type',
            field=models.CharField(choices=[('commercial', 'Commercial / Trade Goods'), ('personal', 'Personal Effects & Household Goods'), ('balikbayan', 'Balikbayan Box (RA 10021)'), ('samples', 'Samples / No Commercial Value'), ('machinery', 'Machinery & Equipment (Capital Goods)'), ('raw_materials', 'Raw Materials & Inputs'), ('ecommerce', 'Online Purchase / E-Commerce'), ('balik_bayan', 'Balik Bayan'), ('courier', 'Courier'), ('sample', 'Sample / Free of Charge'), ('diplomatic', 'Diplomatic')], default='commercial', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipmentdocument',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Commercial Invoice'), ('packing_list', 'Packing List'), ('airway_bill', 'Airway Bill / Bill of Lading'), ('sad', 'Single Administrative Document (SAD)'), ('other', 'Other Supporting Document')], max_length=20),
        ),
    ]
