# Generated by Django 6.0.2 on 2026-06-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_remove_land_sea_shipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdocument',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Commercial Invoice'), ('packing_list', 'Packing List'), ('airway_bill', 'Airway Bill / Bill of Lading'), ('sad', 'FAN Document'), ('payment_proof', 'Payment Proof / BOC Receipt'), ('release_doc', 'Release / Delivery Document'), ('billing_doc', 'Final Billing Document'), ('receipt', 'Billing Receipt / Payment Proof'), ('other', 'Other Supporting Document')], max_length=20),
        ),
    ]
