# Generated by Django 6.0.4 on 2026-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_alter_shipmentdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='estimated_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
