# Generated by Django 6.0.4 on 2026-06-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_shipment_estimated_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='container_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
