# Generated by Django 6.0.4 on 2026-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0016_shipment_container_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='job_order_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
