"""Shared building blocks for supervisor operational report exports.

Keeps reporting-period resolution and the CSV/PDF writers in one place so the
shipment register, user accounts, and audit trail exports stay consistent with
each other and with the existing analytics/intelligence reports.
"""
import csv
from datetime import date, timedelta

from django.http import HttpResponse
from django.utils import timezone


# ── Reporting periods ────────────────────────────────────────────────────────

# key, label. 'custom' falls back to the raw date_from/date_to inputs; '' means
# no date filtering at all.
REPORT_PERIOD_CHOICES = [
    ('', 'All time'),
    ('today', 'Today'),
    ('this_week', 'This week'),
    ('this_month', 'This month'),
    ('last_month', 'Last month'),
    ('this_quarter', 'This quarter'),
    ('this_year', 'This year'),
    ('custom', 'Custom range'),
]

_VALID_PERIODS = {key for key, _label in REPORT_PERIOD_CHOICES}


def _quarter_start(today):
    return date(today.year, 3 * ((today.month - 1) // 3) + 1, 1)


def _parse_date(raw):
    try:
        return date.fromisoformat(raw)
    except (TypeError, ValueError):
        return None


def resolve_report_period(request, *, from_param='date_from', to_param='date_to'):
    """Resolve a reporting period from the request.

    A named ``period`` preset wins over the raw date inputs. ``custom`` (or no
    preset) keeps whatever date_from/date_to were supplied, so existing links
    that only pass dates keep working unchanged.

    Returns a dict with ISO ``date_from`` / ``date_to`` strings (either may be
    ''), the resolved ``period`` key, and a human ``label`` for report headers.
    """
    period = (request.GET.get('period') or '').strip()
    if period not in _VALID_PERIODS:
        period = ''
    raw_from = (request.GET.get(from_param) or '').strip()
    raw_to = (request.GET.get(to_param) or '').strip()

    today = timezone.localdate()
    start = end = None

    if period == 'today':
        start = end = today
    elif period == 'this_week':
        start, end = today - timedelta(days=today.weekday()), today
    elif period == 'this_month':
        start, end = today.replace(day=1), today
    elif period == 'last_month':
        first_this = today.replace(day=1)
        end = first_this - timedelta(days=1)
        start = end.replace(day=1)
    elif period == 'this_quarter':
        start, end = _quarter_start(today), today
    elif period == 'this_year':
        start, end = today.replace(month=1, day=1), today

    if start and end:
        date_from, date_to = start.isoformat(), end.isoformat()
    else:
        # 'custom', '' or an unrecognised preset: honour the raw inputs.
        date_from = raw_from if _parse_date(raw_from) else ''
        date_to = raw_to if _parse_date(raw_to) else ''
        if period == '' and (date_from or date_to):
            period = 'custom'

    label = dict(REPORT_PERIOD_CHOICES).get(period, 'All time')
    if period in ('custom', ''):
        if date_from or date_to:
            label = f"{date_from or 'earliest'} to {date_to or 'latest'}"
        else:
            label = 'All time'

    return {
        'period': period,
        'date_from': date_from,
        'date_to': date_to,
        'label': label,
        'choices': REPORT_PERIOD_CHOICES,
    }


def apply_period(queryset, period, field):
    """Filter ``queryset`` on ``field`` (a date lookup) using a resolved period."""
    if period['date_from']:
        queryset = queryset.filter(**{f'{field}__date__gte': period['date_from']})
    if period['date_to']:
        queryset = queryset.filter(**{f'{field}__date__lte': period['date_to']})
    return queryset


# ── Report metadata block ────────────────────────────────────────────────────

def build_report_meta(request, *, period, filters, total):
    """Standard metadata rows shown at the top of every generated report.

    Returns (label, value) pairs so each writer can render them in its own
    idiom — stacked lines in PDF, two columns in CSV/XLSX.
    """
    user = getattr(request, 'user', None)
    if user is not None and getattr(user, 'is_authenticated', False):
        generated_by = user.get_full_name() or user.username
    else:
        generated_by = 'System'

    if isinstance(period, dict):
        period_label = period.get('label') or 'All time'
    else:
        period_label = str(period or 'All time')

    return [
        ('Generated by', generated_by),
        ('Generated on', timezone.localtime().strftime('%B %d, %Y %H:%M')),
        ('Reporting Period', period_label),
        ('Applied Filters', filters or 'None'),
        ('Total Records', total),
    ]


def format_filters(pairs):
    """Render an ordered mapping of filter name -> value as 'A: x | B: y'."""
    return ' | '.join(f'{label}: {value or "All"}' for label, value in pairs)


# ── Output writers ───────────────────────────────────────────────────────────

def csv_safe(value):
    """Neutralise spreadsheet formula injection.

    Report cells can contain user-supplied text. A cell beginning with =, +, -
    or @ is executed as a formula when opened in Excel or Sheets, so those are
    prefixed with an apostrophe.
    """
    text = '' if value is None else str(value)
    if text[:1] in ('=', '+', '-', '@', '\t', '\r'):
        return "'" + text
    return text


def csv_report_response(filename_stem, title, meta, headers, rows):
    """Build a CSV download with a metadata block above the table.

    UTF-8 BOM so Excel on Windows keeps accents.
    """
    stamp = timezone.localtime().strftime('%Y%m%d_%H%M')
    response = HttpResponse(content_type='text/csv; charset=utf-8')
    response['Content-Disposition'] = f'attachment; filename="{filename_stem}_{stamp}.csv"'
    response.write('﻿')

    writer = csv.writer(response)
    writer.writerow([title])
    for label, value in meta:
        writer.writerow([f'{label}:', csv_safe(value)])
    writer.writerow([])

    writer.writerow(headers)
    for row in rows:
        writer.writerow([csv_safe(cell) for cell in row])
    return response


def csv_multi_section_response(filename_stem, title, meta, sections):
    """Build a CSV download for a multi-table report.

    ``sections`` is a sequence of (title, headers, rows). Each is written as a
    titled block separated by a blank line, which keeps the whole report in one
    file while staying readable in Excel.
    """
    stamp = timezone.localtime().strftime('%Y%m%d_%H%M')
    response = HttpResponse(content_type='text/csv; charset=utf-8')
    response['Content-Disposition'] = f'attachment; filename="{filename_stem}_{stamp}.csv"'
    response.write('﻿')

    writer = csv.writer(response)
    writer.writerow([title])
    for label, value in meta:
        writer.writerow([f'{label}:', csv_safe(value)])

    for section_title, headers, rows in sections:
        writer.writerow([])
        writer.writerow([section_title])
        if headers:
            writer.writerow(headers)
        for row in rows:
            writer.writerow([csv_safe(cell) for cell in row])
    return response


def pdf_meta_flowables(meta, doc_width):
    """Compact two-column metadata block for the top of a PDF report."""
    from reportlab.lib import colors
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.platypus import Paragraph, Table, TableStyle

    label_style = ParagraphStyle('metaLabel', fontName='Helvetica-Bold', fontSize=8, leading=11)
    value_style = ParagraphStyle('metaValue', fontName='Helvetica', fontSize=8, leading=11)
    data = [
        [Paragraph(f'{label}:', label_style), Paragraph(str(value), value_style)]
        for label, value in meta
    ]
    table = Table(data, colWidths=[92, doc_width - 92], hAlign='LEFT')
    table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 1),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 1),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#475569')),
    ]))
    return table


def pdf_report_response(filename_stem, title, meta, headers, rows, *, empty_message='No records match these filters.'):
    """Build a landscape PDF download matching the analytics/intelligence style."""
    from io import BytesIO
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

    from .analytics import _pdf_col_widths  # local import avoids a circular import

    stamp = timezone.localtime().strftime('%Y%m%d_%H%M')
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=landscape(A4),
        rightMargin=24, leftMargin=24, topMargin=24, bottomMargin=24,
    )
    styles = getSampleStyleSheet()
    cell_style = ParagraphStyle('cell', fontName='Helvetica', fontSize=7, leading=9)

    story = [
        Paragraph(title, styles['Title']),
        Spacer(1, 6),
        pdf_meta_flowables(meta, doc.width),
        Spacer(1, 14),
    ]

    body = rows or [[empty_message] + [''] * (len(headers) - 1)]
    table_data = [list(headers)] + [
        [Paragraph(str(cell if cell is not None else ''), cell_style) for cell in row]
        for row in body
    ]
    table = Table(
        table_data,
        colWidths=_pdf_col_widths([headers] + body, doc.width),
        repeatRows=1, hAlign='LEFT',
    )
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1B3358')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 7),
        ('GRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#DCE5EF')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]))
    story.append(table)
    doc.build(story)

    response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{filename_stem}_{stamp}.pdf"'
    return response
