# Generated by Django 6.0.4 on 2026-04-26 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyComputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('freight_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('insurance_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('duty_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dutiable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('customs_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vat_base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_landed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hs_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.hscode')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computation', to='shipments.shipment')),
            ],
        ),
    ]
