# Generated by Django 6.0.4 on 2026-04-26 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0001_initial'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('urgency_level', models.CharField(max_length=10)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lcl_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('fcl_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('air_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('recommended_type', models.CharField(blank=True, choices=[('lcl', 'LCL - Less Container Load'), ('fcl', 'FCL - Full Container Load'), ('air', 'Air Freight')], max_length=10, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('computed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_advisory', to='shipments.shipment')),
            ],
        ),
    ]
