# Generated by Django 6.0.4 on 2026-05-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0002_shippingadvisory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutycomputation',
            name='freight_cost',
        ),
        migrations.RemoveField(
            model_name='dutycomputation',
            name='insurance_cost',
        ),
        migrations.AddField(
            model_name='dutycomputation',
            name='brokerage_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='dutycomputation',
            name='ipf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Import Processing Fee', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='dutycomputation',
            name='items_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dutycomputation',
            name='total_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dutycomputation',
            name='total_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dutycomputation',
            name='customs_duty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total CUD', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dutycomputation',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dutycomputation',
            name='dutiable_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxable Value — sum of all D/V PHP', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dutycomputation',
            name='duty_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dutycomputation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
