# Generated by Django 6.0.4 on 2026-07-19 04:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0010_remove_land_from_shipping_advisory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutycomputation',
            name='bir_dst',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), help_text='BIR Documentary Stamp Tax (default ₱30)', max_digits=15),
        ),
    ]
