# Generated by Django 6.0.4 on 2026-04-26 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('submission', 'New Submission'), ('status_update', 'Status Update'), ('computation', 'Computation Complete'), ('advisory', 'Shipping Advisory'), ('payment', 'Payment Required'), ('approved', 'Shipment Approved'), ('rejected', 'Shipment Rejected'), ('general', 'General')], default='general', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
