# Generated by Django 6.0.4 on 2026-05-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('submission', 'New Submission'), ('status_update', 'Status Update'), ('computation', 'Computation Complete'), ('advisory', 'Shipping Advisory'), ('payment', 'Payment Required'), ('approved', 'Shipment Approved'), ('rejected', 'Shipment Rejected'), ('arrived', 'Shipment Arrived'), ('computed', 'Computation Ready'), ('for_revision', 'For Revision'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
